version: '3.8'

services:
  api:
    container_name: podrida-app-backend
    image: ghcr.io/martinbarreiroo/podrida-app-backend:latest
    ports:
      - "8000:8080"
    environment:
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: podrida-app-db
      DB_HOST: db
      DB_PORT: 5432
      DOCKER_PORT: 8080
    env_file:
      - .env
    restart: always

  db:
    container_name: podrida-app-db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
    restart: always

volumes:
  pgdata:
