name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Download and extract New Relic Java agent
        run: |
          mkdir -p newrelic
          curl -L https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip -o newrelic/newrelic-java.zip
          unzip newrelic/newrelic-java.zip -d newrelic
          # Optional: overwrite default newrelic.yml with your custom config
          echo "license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}" > newrelic/newrelic/newrelic.yml
          mv newrelic/newrelic/* newrelic/

      - name: Build and Tag Docker Image
        run: |
          docker build \
            --build-arg NEW_RELIC_JAR=./newrelic/newrelic.jar \
            --build-arg NEW_RELIC_YML=./newrelic/newrelic.yml \
            -t ghcr.io/${{ github.repository_owner }}/podrida-app-backend:latest .

      - name: Push Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/podrida-app-backend:latest
